### PR TITLE
Searches

### PR DESCRIPTION
**Pull request by nyov**
This has several improvements to the search spiders.
It implements these Milestone features:
✓ linkcheck results (ignore 404 and other errors before replying)
✓ detect and ignore spam while fetching more results
✓ ignore more results from a TLD considered spam

Search results are now much more informational (before the bot would only know "text" and "url" content for a particular search result). Now it keeps information about `title`, `description`, `image_link` and other information (where available). These are now available for formatting the results as a message template (`BOTCMD_IMAGESEARCH_RESULT_TEMPLATE`) and defined in `SearchResultItem`.

Additionally there should be less occurances of no results for nsfw subs now (trying to search without SafeSearch restrictions). [This should possibly become configurable, so searches for public/sfw requests would be done with safesearch active.]

The rest of the changes is trying to better handle things in the event of errors (such as the initial search request failing).

/edit:
Because of the link-checking, the bot will now take somewhat longer to finish a search.
In particular when pages are not responding and the request hangs until hitting a timeout.
Because of this there is now a `DOWNLOAD_TIMEOUT_LINKCHECK` option to configure this, which has a shorter timeout than regular requests (30 seconds). But if a timeout is hit, the result will be discarded, so it shouldn't be set too low, some pages might simply be slow to respond.

10 minute runs will probably be the norm now, with the search, then the reddit spam check run and finally maybe hitting a reddit ratelimit of some more minutes, before being able to reply.

### CODE REVIEW

**Comment by nyov** [comment]
Adding another feature here: make sure the search results post to reddit by dropping results until the message fits reddit's post size limit, if it was longer. (So the bot has a way to recover if some links are uncommonly long or such.)
Upping the search results to ~15 per SE would be okay now, and the bot will magically fit as many as possible before posting.

@tek0011 
I'll PR the wordcloud features as soon as you get around to check and merge this one.

**Comment by tek0011** [comment]
going to try to implement this today.
but before I do, how can we create a filter list for the word cloud?  Needs
to gather words from search results > filter through a maintained list >
output

On Fri, May 13, 2016 at 7:50 AM, nyov <notifications@github.com> wrote:

> Adding another feature here: make sure the search results post to reddit
> by dropping results until the message fits reddit's post size limit, if it
> was longer. (So the bot has a way to recover if some links are uncommonly
> long or such.)
> Upping the search results to ~15 per SE would be okay now, and the bot
> will magically fit as many as possible before posting.
>
> @tek0011 <https://github.com/tek0011>
> I'll PR the wordcloud features as soon as you get around to check and
> merge this one.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/pull/91#issuecomment-219033632>
>



-- 
Jeff

**Comment by nyov** [comment]
I've already added that feature after your mail.
To preview the wordcloud stuff, see here: https://github.com/nyov/reddit_info_bot/compare/master...nyov:wordcloud

There is a config setting to add stopwords in it (filter out words before building the wordcloud):
https://github.com/nyov/reddit_info_bot/compare/master...nyov:wordcloud#diff-e95a003d7a3bb9760ef8bab93a4165beR143

I can only create the pull request for that after this one here was merged, sorry.
Splitting the code into two PRs means I can assign both to their respective Milestones.
But you can merge them "back to back" and test them together, after merging both.
If you could do this merge now, I'll create the second PR?

**Comment by tek0011** [comment]
Ill be able to merge it probably in the next 3 hours.

On Mon, May 16, 2016 at 9:33 AM, nyov <notifications@github.com> wrote:

> I've already added that feature after your mail.
> To preview the wordcloud stuff, see here: nyov@master...nyov:wordcloud
> <https://github.com/nyov/reddit_info_bot/compare/master...nyov:wordcloud>
>
> There is a config setting to add stopwords in it (filter out words before
> building the wordcloud):
> nyov@master...nyov:wordcloud#diff-e95a003d7a3bb9760ef8bab93a4165beR143
> <https://github.com/nyov/reddit_info_bot/compare/master...nyov:wordcloud#diff-e95a003d7a3bb9760ef8bab93a4165beR143>
>
> I can only create the pull request for that after this one here was
> merged, sorry.
> Splitting the code into two PRs means I can assign both to their
> respective Milestones.
> But you can merge them "back to back" and test them together, after
> merging both.
> If you could do this merge now, I'll create the second PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/pull/91#issuecomment-219440399>
>



-- 
Jeff

**Comment by nyov** [comment]
Alright!

**Pull request merged**
