### PR TITLE
Next changes - oauth, logging

### PR DESCRIPTION
**Pull request by nyov**
This is not quite all I had in mind for the next push, but the rest should follow in the next few days.

The only real feature in this one is OAuth, I believe.
Potential pitfall for the upgrade is another change-around in some config variable names (alas, still not really happy with my naming :( -- might change it all some more, later down the road, and compartmentalize the bot commands into various `BotCommand` classes with their own settings.)

Well, OAuth. That's a whole new bag of strangeness. It's not really hard to get done, but more hard to explain in setting up. And then with two accounts.

Thus I went with the simplest way (to get it working) for now, so all the script wants here is a `CLIENT_ID` and `SECRET_TOKEN` (in addition to the username + password), for both accounts.
Without those it will keep using password login, so should stay working either way.

Accounts setup is at https://www.reddit.com/prefs/apps/ (once for both accounts), the app needs to be of type "script".
The redirect url is required (but not used by us, yet, 'http://127.0.0.1:65010/authorize_callback' is the default that can be put in there).
After the app-creation, the `CLIENT_ID` can be found beneath "personal use script", and where it says "secret", thats the `SECRET_TOKEN` for the bot.

And that should be all.

### CODE REVIEW

**Comment by nyov** [comment]
And here's the next stuff.
That implements logging and the version numbering, and various changes to support that.
May thou suffocate in logs ;)

**Comment by tek0011** [comment]
Thanks.  Ill test it out this weekend.  Im still trying to get a hold of
spambot owner, to figure out this database locking.  Thats an integral part
of not getting the bot banned.

On Wed, Oct 28, 2015 at 11:14 AM, nyov <notifications@github.com> wrote:

> And here's the next stuff.
> That implements logging and the version numbering, and various changes to
> support that.
> May thou suffocate in logs ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/pull/79#issuecomment-151896977>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
Hm, in that case I might have some more changes by then.
And I'm working on polling only updates of the spam-db, which should make this more friendly on the database, at least I've seen much less errors in the few tests I did.
Also will do this periodically at runtime then, instead of on start, to keep it up-to-date.

**Comment by tek0011** [comment]
From what I can tell on the git diff's this commit was already merged.  I think.

**Comment by tek0011** [comment]
Ya I cant get this thing to merge.

**Comment by nyov** [comment]
Are you certain that it merged? The last commit here is only 13 days old.
(And I'm not sure why github says commited in October, thats the AuthorDate. WTF.
The actual commit date on that last one is `Tue Feb 2 23:10:32 2016 +0000`)

I'll have a look.

**Comment by tek0011** [comment]
Ya.  Every time I attempted to merge, nothing would happen.  I was 90% sure
that back in Oct, I had already merged that last commit.  Now Im just
really confused on where its at lol.

**Comment by nyov** [comment]
Okay, solved.

**Pull request merged**
