### PR TITLE
New search code, replacing search proxy

### PR DESCRIPTION
**Pull request by nyov**
So far a "drop-in" replacement for the current search,
but is a bit more greedy at pulling in results (taking all it can "see" on a page before it might have to follow a pagination link)
before spam-filtering - so if there is lots of "spam" being filtered out there may be more results left over in some cases.

### CODE REVIEW

**Comment by tek0011** [comment]
Thanks.  Ill check it out this week.  Ill send you the other half of the
payment this weekend as well.
What issues do you expect to be found with this update?  We don't want to
have too much spam.  The more spam that gets passed, the faster the bot
will get banned.

On Tue, Mar 22, 2016 at 7:52 AM, nyov <notifications@github.com> wrote:

> So far a "drop-in" replacement for the current search,
> but is a bit more greedy at pulling in results (taking all it can "see" on
> a page before it might have to follow a pagination link)
> before spam-filtering - so if there is lots of "spam" being filtered out
> there may be more results left over in some cases.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/tek0011/reddit_info_bot/pull/85
> Commit Summary
>
>    - rename variable
>    - update loop
>    - goodbye proxy search
>    - remove (broken) search code
>    - hello scrapy
>    - Merge branch 'search'
>
> File Changes
>
>    - *M* config_example.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-0> (4)
>    - *M* reddit_info_bot/commands.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-1> (39)
>    - *M* reddit_info_bot/default_settings.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-2> (8)
>    - *M* reddit_info_bot/reddit.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-3> (23)
>    - *M* reddit_info_bot/search.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-4>
>    (288)
>    - *M* reddit_info_bot/settings.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-5> (6)
>    - *A* reddit_info_bot/spiders/__init__.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-6>
>    (124)
>    - *A* reddit_info_bot/spiders/search.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-7>
>    (381)
>    - *M* reddit_info_bot/util.py
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-8> (5)
>    - *M* requirements.txt
>    <https://github.com/tek0011/reddit_info_bot/pull/85/files#diff-9> (1)
>
> Patch Links:
>
>    - https://github.com/tek0011/reddit_info_bot/pull/85.patch
>    - https://github.com/tek0011/reddit_info_bot/pull/85.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/pull/85>
>



-- 
Jeff

**Comment by nyov** [comment]
I must admit I do not know where spam could get past us here.
After doing some preliminary checks against rarchives-db, at the last stage all remaining urls are checked against the rarchives moderator bot and reddit's own filters, by submitting them in the parser sub.
At that point anything flagged as spam link/text, either by reddit or the rarchives mod, is dropped.
If _they_ didn't consider it spam at that point, I don't know by what criteria it should be spam?

Did you see any issue with this filtering? Are there any links that were flagged spam but were still posted by the bot? When I checked this code after the last update , it seemed to work fine?
Is anyone is banning the bot?

**Comment by nyov** [comment]
> What issues do you expect to be found with this update?

The only part that changed is how the results are found. That should mean, either it breaks completely or it behaves as before. So far it didn't break in my tests ;)

**Comment by tek0011** [comment]
There are a couple places that are banning the bot.  Mostly because it just
can't find the results.  That being said I think we should shift our
focus.  The replies that the bot gives, when there is no information is
boring.  Its why the bots getting banned from some popular subs.  I think
to help alleviate that, we should work on the following milestone:

*-Take text from links and apply them to a word cloud. Provide link to word
cloud. Filter for common words. Take top x words and make them a keyword
for other things found (like wiki bot)*
*Milestone:  $150*

I would also like to add to this, that we could take similarly found
results and provide a nicely formatted table of those results.  That way
when we get links that do not have any reverse findings, we could still
provide a word cloud from the bodys of the links provided, as well as a
nice table of links to other "similar images".

This would make it so that even when the bot can't find a reverse, it still
provides users with links, content and possible words to follow.

**Comment by tek0011** [comment]
fyi, latest build is completely broken

On Thu, Mar 24, 2016 at 6:38 AM, Jeff <thecptsparrow@gmail.com> wrote:

> There are a couple places that are banning the bot.  Mostly because it
> just can't find the results.  That being said I think we should shift our
> focus.  The replies that the bot gives, when there is no information is
> boring.  Its why the bots getting banned from some popular subs.  I think
> to help alleviate that, we should work on the following milestone:
>
> *-Take text from links and apply them to a word cloud. Provide link to
> word cloud. Filter for common words. Take top x words and make them a
> keyword for other things found (like wiki bot)*
> *Milestone:  $150*
>
> I would also like to add to this, that we could take similarly found
> results and provide a nicely formatted table of those results.  That way
> when we get links that do not have any reverse findings, we could still
> provide a word cloud from the bodys of the links provided, as well as a
> nice table of links to other "similar images".
>
> This would make it so that even when the bot can't find a reverse, it
> still provides users with links, content and possible words to follow.
>



-- 
Jeff

**Comment by nyov** [comment]
Ah, the work-in-progress PR wasn't meant for merge, yet. I'll have to fix that.

**Comment by tek0011** [comment]
Darn.  I should stop merging things so early.  It was like 5am and I hadn't
woken yet.  Wonder why it told me the merge request was ok and didnt want
me to do it from the servers local repo.

On Thu, Mar 24, 2016 at 8:40 AM, nyov <notifications@github.com> wrote:

> Ah, the work-in-progress PR wasn't meant for merge, yet. I'll have to fix
> that.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/pull/85#issuecomment-200837903>
>



-- 
Jeff

**Comment by nyov** [comment]
My fault for opening it. I'll correct it with a force push.

**Pull request merged**
